# Generated by Django 5.2.6 on 2025-09-10 01:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('Nike Mercurial', 'nike mercurial'), ('Nike Tiempo', 'nike tiempo'), ('Nike Phantom', 'nike phantom'), ('Ortuseight Catalyst', 'ortuseight catalyst'), ('Adidas F50', 'adidas f50'), ('Adidas Predator', 'adidas predator')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
