# Generated by Django 5.2.5 on 2025-09-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sepatu Futsal', 'sepatu futsal'), ('Sepatu Bola', 'sepatu bola')], default='update', max_length=20),
        ),
    ]
